#!/usr/bin/env python
# coding: utf-8
import os
import sys
import hashlib

from docopt import docopt

import flask

from leselys.web import app
from leselys.logger import stream_logger

doc = """Leselys-web is a Web Interface for Leselys.

Usage:
  leselys-web serve [--host=<address>] [--port=<port>] [--debug]
  leselys-web -h | --help
  leselys-web -v | --version

Options:
  --host=<address>    Address to bind webserver on [default: 127.0.0.1]
  --port=<port>       Port to listen for webserver [default: 5000]
  --debug             Enable Debug mode for Flask [default: false]
  -h --help           Show help
  -v --version        Show version

"""

if __name__ == '__main__':
    args = docopt(doc, version='0.1')
    debug = args.get('--debug')
    address = args.get('--host')
    port = args.get('--port')

    app.run(host=address, port=int(port), debug=debug)
